language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: npm
  email: bvdrucker@gmail.com
  api_key:
    secure: MJxTzyOdScVg/Agp5PAOCQQPkQDJa47EDHsyv0/hwU4OcRvYKc3iBdPHx7QXlqOnX1Z2lgALU9XHlVnR7huv/7OTC/tpGMdn/50r9I/AG+aaam29WxIA2Bbt2AHtA2sk+/KjMP/2A0J7v5g27MSL906Wr+x+TJKszOl7GYA5yvA=
  on:
    tags: true
    repo: valet-io/stream-to-promise
